### ISSUE TITLE
Replace not working

### ISSUE THREAD

**Issue by HarryFT** [facelessuser/Rummage#435] opened 2021-12-20 13:39 UTC
Hey, I'm using Find and Replace in this tool with Search Chains, but it doesn't seem to actually replace in the files, I think their all getting skipped. It's found matches but just doesn't seem to act on them.

**Comment by facelessuser** [comment] 2021-12-20 14:51
Can you provide am example of chains not working?

**Comment by facelessuser** [comment] 2021-12-20 15:19
Okay, here is an example:

<img width="734" alt="Screen Shot 2021-12-20 at 8 05 27 AM" src="https://user-images.githubusercontent.com/1055125/146788494-d0bb3275-d8fd-4a48-8c54-d7fb4164cc3c.png">

The patterns are as follows:
 
- `test1`: `!` -> `world!`
- `test2: `(hello)(world)` -> `\1 \2`

These are combined into a chain called `hello-world`:

<img width="472" alt="Screen Shot 2021-12-20 at 8 08 50 AM" src="https://user-images.githubusercontent.com/1055125/146788844-1e092c27-3fc0-4784-b6af-97e00cc959f3.png">

I create a simple file called `hello.world` with the text:

```
Hello!
```

I run the find/replace on the file `hello.world` and it replaces the content with:

```
Hello world!
```
---

Often when I get issues like this it is usually user misunderstanding. Usually on of these two.

1. A misunderstanding related to how Rummage chains work.

    Keep in mind that Rummage chains run each pattern on the entire buffer before running the second pattern in the chain. Because of how the chain passes work, the example above transformed the text in the file as follows: `Hello!` -> `Helloworld!` -> `Hello world!`.

2. The user regex doesn't match what they think it should match. This is crucial as well-formed regex that matches exactly what it is supposed to is key.

---

Now, I'm not being dismissive. If I have an actual example that is not performing as expected, I'm more than happy to look deeper, I'm more just demonstrating that on the surface, it appears to be working, and generally, such complaints are usually user error. But there may be some kind of combination of settings or something that is breaking things, so a minimal example that is failing would really help shine some light on the real issue.

**Comment by HarryFT** [comment] 2021-12-20 15:33
Interesting, I'm finding it is replacing on your example. An example in my chain that I'm not seeing working is replacing .. (double periods) with a single period, and rather than regex, I've used a literal find and replace. My chain is using both literal and regex strings so I wonder if that could be affecting it? Or could it possibly be that it's not reaching that point of the chain as its not detecting anything on the earlier searches?

**Comment by facelessuser** [comment] 2021-12-20 15:47
I'm not sure as I don't have an example to look at. I can only speculate.

**Comment by facelessuser** [comment] 2021-12-20 15:56
Hmm, I may have stumbled on something. I changed my example to use a literal text replace on the first pattern, and the second pattern worked, but it seemed to use regex search but literal replace on the second pattern...

**Comment by HarryFT** [comment] 2021-12-20 15:58
I found another example. So this one is meant to capitalise Pro Tools, but it doesn't seem to have any effect even on its own (outside of a chain). It's coming up as a match but doesn't seem to be writing the replacement to the file.
![Screenshot 2021-12-20 at 3 55 24 pm](https://user-images.githubusercontent.com/48953096/146795897-2995687f-9606-46ff-868a-0dfae293fa21.png)

**Comment by facelessuser** [comment] 2021-12-20 16:03
I don't want to confuse the discussion. I do think I see an issue when mixing literal find and replace with regex find and replace as stated above.

I'm not sure about this `pro tools` literal replace though. I see no issue with the pattern in and of itself. Is this not working by itself or only in a chain? I say this as there seems to be nothing fundamentally wrong with this when run in the tester.

<img width="576" alt="Screen Shot 2021-12-20 at 9 01 06 AM" src="https://user-images.githubusercontent.com/1055125/146796537-91d1139d-d380-4fd9-af6c-e0cce35dedd4.png">

**Comment by facelessuser** [comment] 2021-12-20 16:16
I've found the source of the literal/regex combo bug. Literal is assumed `False` as a default, but when any pattern in the chain is literal, we set the mode to `True`, but non-literal patterns never set it back to `False`. Ensuring that each pattern in the chain sets this mode fixes this issue.

So far, that is the only bug I've found, and we should have a fix for it in the next release.

**Comment by facelessuser** [comment] 2021-12-20 16:25
Fix is on `master`. You can try installing that and see if your issues are resolved. This may resolve your `pro tools` issue assuming the issue existed due to the mixed literal/regex chain issue, if not please provide more details and if I can confirm an issue, I'll try to get it resolve before the next release.

**Comment by HarryFT** [comment] 2021-12-20 16:40
![Screenshot 2021-12-20 at 4 29 06 pm](https://user-images.githubusercontent.com/48953096/146801533-9a10ca18-5277-49e8-a55d-6141b9fbaad3.png)
Trying to update but I seem to get this error. Also sorry I'm such a noob lol, just getting to grips with running python programs etc. I've tried uninstalling and reinstalling through pip but I think it's cached the older version?

**Comment by facelessuser** [comment] 2021-12-20 16:47
Sorry, I didn't really explain. The fix is not yet released. You can install the unreleased `master` branch with this:

```
python3 -m pip install -U git+https://github.com/facelessuser/Rummage.git
```

**Comment by HarryFT** [comment] 2021-12-20 16:54
![Screenshot 2021-12-20 at 4 53 38 pm](https://user-images.githubusercontent.com/48953096/146803455-92ef3308-3dd8-4664-bb17-65ac27a8db97.png)
![Screenshot 2021-12-20 at 4 53 32 pm](https://user-images.githubusercontent.com/48953096/146803458-f999a000-f7a6-44a2-aaad-4e16fc939429.png)
Seems to be throwing me these errors now when I try to launch it?

**Comment by facelessuser** [comment] 2021-12-20 17:03
Did you use the **exact** python version you installed Rummage with originally? Did you ensure Rummage was closed before you updated? There is nothing major between `master` and the last released version.

**Comment by facelessuser** [comment] 2021-12-20 17:03
Worse case, close all instances of rummage, uninstall rummage, and then re-install rummage.

**Comment by facelessuser** [comment] 2021-12-20 17:05
I've updated locally with no issues, so I can confirm that nothing breaking has been included in the most recent Rummage on `master`.

**Comment by HarryFT** [comment] 2021-12-20 17:14
Ok, I think I'm in the new version now (I got the changelog show up on startup with that fix). Though I'm still finding that running individual searches isn't working as expected. What I don't understand is that it seems to find a match, but when I run the Find and Replace again, I'm getting the same number of matches. So I'd assume that it's finding the Find string, but just isn't replacing it. 

![Screenshot 2021-12-20 at 5 11 40 pm](https://user-images.githubusercontent.com/48953096/146805812-ed907e0c-fbff-4c63-85a0-9dfbcc149ad7.png)

This was using the double periods to single periods search I mentioned previously. Maybe the files are readable but not writable by rummage? or possibly I need to reinstall the dependancies as we may have different versions?

**Comment by facelessuser** [comment] 2021-12-20 17:22
I need actual patterns that I can copy and paste and help debug with. I see an error in the bottom right-hand corner. See the red circle with an X? I think you have some things failing. Maybe bad patterns. Can you click that and look at the errors?

**Comment by facelessuser** [comment] 2021-12-20 17:23
If you provide the patterns I can try things out here and most likely identify your issue.

**Comment by HarryFT** [comment] 2021-12-20 17:46
I think this could be it! What can I do to give rummage permission?
![Screenshot 2021-12-20 at 5 11 40 pm](https://user-images.githubusercontent.com/48953096/146805812-ed907e0c-fbff-4c63-85a0-9dfbcc149ad7.png)

**Comment by facelessuser** [comment] 2021-12-20 18:12
Okay, I'm not entirely sure. I assume at one point I was prompted for permissions to access Downloads and Documents, etc. 

I use Python installed via `brew`, so maybe permissions are handled automatically. Maybe I was prompted for permission and accepted, or maybe I didn't. If you are using Python's official installer, to install Python, maybe you have to give its app permission to access Downloads folder?

Maybe you were prompted and ignored it?  Rummage doesn't directly ask for permissions, I think this is done by Python 🤷🏻 ? I honestly don't recall what I did on my recent setup, but I have access to Downloads etc. I don't see anything in my macOS `Preferences/Security & Privacy` options that is related to Python, but maybe that is because I use Python installed through brew.  If you aren't using brew Python, maybe you have to give Python permission?

**Comment by facelessuser** [comment] 2021-12-20 18:24
Another question is whether the specific folder under Downloads has permissions that Rummage cannot access, or Downloads itself is denying access. Can you access files directly under Downloads with Rummage, or is it specific folders under Downloads denying access? Check your folder permissions, are they locked under admin? The user? Rummage doesn't run under root by default, so I imagine it will have access to your user folders assuming they aren't locked with admin permissions or some other permissions.

**Comment by facelessuser** [comment] 2021-12-22 17:06
I'm prepping to formally release a fix for the chaining issue. I should have a release out later today.

Unfortunately, your permission issue is very specific to your machine. Mac usually prompts the user when an application needs general access to a specific folder. But, even if the application is allowed to access the folder, there are still folder permissions that may affect access. For instance, a folder with `root` permissions may not be accessible by an application with `user` permissions. If `root` privileges are needed for Rummage, Rummage must be run under `root`, there are no dialogs currently available to elevate access to allow access to files and folders with `root` permissions.

I am still unclear about whether access is entirely denied or only write access. If you are able to find results in a file, but not replace changes, this would lead me to believe you are trying to replace within a file with "read only" permissions. You'd have to make the file read/writable before Rummage could do any replacements.

Without further information about the file(s) in question, I cannot advise further. If you want specific help regarding a specific file that is being denied, I could potentially help debug, but you would need to provide some more information, like the current permissions that are currently applied to that file.

**Comment by facelessuser** [comment] 2021-12-23 14:39
I'm going to go ahead and close this as the only identified bug was fixed. The rest seems to be a local file permission issue. If file permissions would like to be discussed further, the discussion could be moved here: https://github.com/facelessuser/Rummage/discussions.

**Comment by facelessuser** [comment] 2021-12-23 14:39
New release has been tagged.

**Closed by facelessuser** 2021-12-23 14:39 UTC
Labels: S: triage
