### ISSUE TITLE
Minor Interface Improvements

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#249] opened 2018-07-05 08:19 UTC
Using Rummage for some time, and found some little things that could greatly improve the overall experience of Rummage. Here are my thoughts, hope other users will share their comments if they sound useful or not.

1. Allow to hide/re-order columns in **Files/Content** tabs. For example, File contains these columns - **File/Matches/Extensions/Size/Path/Encoding/Modified/Created**
I'd love to hide and re-order some columns... I don't know about others, but **Path** column is the most important to me (after File column, obviously). Now, before Path is listed, Rummage also lists Extension (which doesn't make sense to me at all because extension is also listed in File column) and size (well, size might be important too, but not as important as Path, which is only displayed later).

2. Respect system date/time format. My system is configured to display dates in international format: **Y-m-d** (like 2018-07-05). For some reason, Rummage still displays dates using format like "Mon Jul 2 12:17:30 2018", which is slightly more difficult to read than international format. If it's difficult to auto obtain system settings, maybe it's possible to enable users to define their own date/time format in settings? Using standard variables (Y for year, H for hour, etc., like in other apps).

3. Don't auto focus "**Search in**" field when coming back from Files or Content tab back to Search tab. When I view matches in Files tab and come back to Search tab, my only intention is to perform a new search (otherwise, I would just close Rummage after reviewing Files tab if I don't need to find new matches). Now, if I start typing some new match, it replaces "Search in" field. Sure, I can click TAB 2 times to go to "**Search for**" field or use a mouse, but it annoys a little, especially because I usually perform hundreds of searches a day. I think it would make more sense to auto-focus "**Search for**" field or don't focus any field at all.

Just my thoughts, hope you will share your opinion too.

**Comment by facelessuser** [comment] 2018-07-05 13:14
@toxpal, thanks for the suggestions.  In the future, if you could make similar requests as separate issue, it helps me to address each one as I can comment and close each issue individually.

- > Allow to hide/re-order columns in Files/Content tabs. For example, File contains these columns - File/Matches/Extensions/Size/Path/Encoding/Modified/Created
I'd love to hide and re-order some columns... I don't know about others, but Path column is the most important to me (after File column, obviously). Now, before Path is listed, Rummage also lists Extension (which doesn't make sense to me at all because extension is also listed in File column) and size (well, size might be important too, but not as important as Path, which is only displayed later).

    This is something I'd actually like to implement one day if I can get it in.  The only reason it is not in is due to the fact that the wxPython API doesn't make such things easy.

    The ordering part may actually be the easiest thing to do.  You can currently drag columns to new locations, but Rummage does not remember order changes.  I'm not sure the impact it would have on internal code, but if possible, I wouldn't mind adding the feature to remember ordering.

    Hiding is a bit trickier as wxPython does not have an API for this, and there are currently only hacks to pull this off, or more complexity that must be added to pull this off.  I may revisit this and see if I can come up with a way, but that is the main reason it is not currently available.

- Respect system date/time format. My system is configured to display dates in international format: Y-m-d (like 2018-07-05). For some reason, Rummage still displays dates using format like "Mon Jul 2 12:17:30 2018", which is slightly more difficult to read than international format. If it's difficult to auto obtain system settings, maybe it's possible to enable users to define their own date/time format in settings? Using standard variables (Y for year, H for hour, etc., like in other apps).

    I can understand the desire for this request. I'll look into to it.  At the very least, maybe I can provide a simple toggle for international format, but maybe we could provide a template instead.  I'll think about this.

- > Don't auto focus "Search in" field when coming back from Files or Content tab back to Search tab. When I view matches in Files tab and come back to Search tab, my only intention is to perform a new search (otherwise, I would just close Rummage after reviewing Files tab if I don't need to find new matches). Now, if I start typing some new match, it replaces "Search in" field. Sure, I can click TAB 2 times to go to "Search for" field or use a mouse, but it annoys a little, especially because I usually perform hundreds of searches a day. I think it would make more sense to auto-focus "Search for" field or don't focus any field at all.

I don't understand this request.  What to you mean by:

> Don't auto focus "Search in" field when coming back from Files or Content tab back to Search tab.

Rummage I think autofocuses **Search for** on application load, and that is it (on macOS this doesn't always work due to a quirk, but it at least attempts to).  In all other cases, it just reacts to what you select or tab to.  Is it something your OS is doing?

**Comment by toxpal** [comment] 2018-07-05 13:43
> In the future, if you could make similar requests as separate issue, it helps me to address each one as I can comment and close each issue individually.

Sure, will do. Didn't want to "spam" you with multiple requests separately.

> Rummage I think autofocuses Search for on application load, and that is it (on macOS this doesn't always work due to a quirk, but it at least attempts to). In all other cases, it just reacts to what you select or tab to. Is it something your OS is doing?

Yes, it auto focus on **Search for** field on load and it works perfectly on Linux. However, if I click Files or Content tab, and then click Search tab again, input is focused on **Search in** field. So every time I need to find a new match, I need to either click TAB 2 times after switching to Search, or move and click mouse over **Search in** field.

**Comment by facelessuser** [comment] 2018-07-05 13:50
I'm almost certain this is an OS thing. I can't reproduce such behavior in Windows, and I won't be near my mac until later today, but I don't recall this behavior.

The idea was to not auto focus at all during tab select, so there is no code that does that. It should have whatever was last selected still selected. At least that is how it works for me on the platforms I use it on. Your OS most likely has logic that kicks in for tabs. Maybe Ubuntu does this as well... Normally I'm in Mac or Windows, so I'm not sure if this occurs in Ubuntu off the top of my head.

**Comment by facelessuser** [comment] 2018-07-05 13:59
If you focus something in the other tabs, it's possible nothing will be selected in the search tab when you return, but I'm unaware of any auto focusing outside of the initial onload event. I'll try this out on Ubuntu when I'm near a Linux box next week.

**Comment by toxpal** [comment] 2018-07-05 18:22
Maybe it's OS thing then... When I open Rummage, **Search in** field is highlighted, but input is focused on **Search for** field. However, it's enough to click Files Tab, click Search tab again, and focus is now on **Search in** field

This is how it looks when I start - https://s33.postimg.cc/ruvmzpyn3/rummage.png

**Comment by facelessuser** [comment] 2018-07-05 18:30
Yup, that is as I suspected. The OS must select the first tab stop within a tab when the tab control is selected.

There are a number of cases like this I fight against to try and provide consistent behavior across OSs.

I **could** force a selection under the search tab when it gains focus. Maybe it is specific to GTK. If so, I could force it on Linux only.

GTK has had issues I've had to work around before. I have had to disable auto complete search entries on Linux just because the timing of events are too different in GTK.

**Comment by facelessuser** [comment] 2018-07-08 14:52
Commenting on time.  For some reason I never realized I put the year after the time of day...shows how much I look at that.  I will group date together with time following:

```
1995-02-04 24:00:00
```

I think since this is used by people from around the world, it makes sense to just conform to a standard most recognizable.

I will most likely provide a form similar to the way it is now, but with corrections that make more sense.  We'll just make this a global option to select forms.

**Comment by facelessuser** [comment] 2018-07-08 15:00
Ahh, year after time is a result of calling `time.ctime`.  That is just the Python about for that function.  It does not account for locale.

**Comment by facelessuser** [comment] 2018-07-08 16:06
Issues have been split out in to their own respective issues.  Closing this as a duplicate as we are now tracking each issue separately.

**Closed by facelessuser** 2018-07-08 16:06 UTC

**Comment by facelessuser** [comment] 2019-05-11 02:15
FYI, re-ordering of columns will be available in the next release.

**Comment by toxpal** [comment] 2019-05-11 10:03
Sounds great, thank you for your hard work.
